### ISSUE TITLE
Authorisation fail

### ISSUE THREAD

**Issue by iKisliy** [thii/WooCommerceSDK#1]
Troubled with authorisation. API is on, keys are right. log: SUCCESS: {
    errors =     (
                {
            code = "woocommerce_api_authentication_error";
            message = "\U041f\U0430\U0440\U0430\U043c\U0435\U0442\U0440 oauth_consumer_key \U0443\U0442\U0435\U0440\U044f\U043d";
        }
    );
}

**Comment by thii** [comment]
As mentioned in my email earlier, your site has to be SSL enabled in order to use this.
