### ISSUE TITLE
Carthage update issues

### ISSUE THREAD

**Issue by Lucania001** [thii/WooCommerceSDK#2]
During install, carthage update fails on 

*** Building scheme "ObjectMapper-Mac" in ObjectMapper.xcworkspace

**Comment by thii** [comment]
What is the command line that you used?

**Comment by Lucania001** [comment]
Tried carthage update --platform iOS and carthage update.

**Comment by Lucania001** [comment]
Here is the trace in case

*** Building scheme "ObjectMapper-iOS" in ObjectMapper.xcworkspace
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Transforms/TransformType.swift:30:2: error: expected declaration
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Transforms/TransformType.swift:33:47: error: use of undeclared type 'Object'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Transforms/TransformType.swift:34:30: error: use of undeclared type 'Object'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Transforms/TransformType.swift:34:42: error: use of undeclared type 'JSON'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:126:65: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:140:65: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:154:65: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:168:66: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:182:66: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:196:66: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:210:74: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:224:74: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:238:74: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:320:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:320:98: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:334:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:334:98: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:348:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:348:98: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:432:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:432:117: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:444:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:444:117: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:456:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:456:117: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:468:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:468:118: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:485:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:485:118: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:502:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:502:118: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:556:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:556:104: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:571:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:571:104: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:585:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:585:104: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:636:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:636:110: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:652:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:652:109: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:668:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:668:110: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:723:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:723:122: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:739:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:739:122: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:756:58: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:756:122: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:251:122: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:261:135: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:271:83: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:271:129: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:277:96: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:277:150: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:76:7: error: binary operator '<-' cannot be applied to operands of type 'T' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:81:7: error: binary operator '<-' cannot be applied to operands of type 'T?' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:86:7: error: binary operator '<-' cannot be applied to operands of type 'T!' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:93:7: error: binary operator '<-' cannot be applied to operands of type '[T]' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:98:7: error: binary operator '<-' cannot be applied to operands of type '[T]?' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:103:7: error: binary operator '<-' cannot be applied to operands of type '[T]!' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:110:7: error: binary operator '<-' cannot be applied to operands of type '[String : T]' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:115:7: error: binary operator '<-' cannot be applied to operands of type '[String : T]?' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:120:7: error: binary operator '<-' cannot be applied to operands of type '[String : T]!' and '(Map, EnumTransform<_>)'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:127:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:129:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:132:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:133:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:141:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:143:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:146:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:147:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:155:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:157:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:160:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:161:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:169:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:171:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:174:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:183:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:185:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:188:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:197:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:199:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:202:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:211:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:213:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:216:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:225:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Document** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
s/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:227:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:230:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:239:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:241:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:244:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:321:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:323:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:324:24: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:326:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:327:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:335:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:337:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:338:24: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:340:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:341:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:349:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:351:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:352:24: error: 'Object' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:354:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:355:24: error: 'JSON' is not a member type of 'Transform'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:433:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:445:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:457:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:469:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:486:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:503:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:557:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:559:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:563:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:572:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:574:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:577:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:586:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:588:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:591:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:637:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:653:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:669:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:724:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:726:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:730:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:740:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:742:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:746:8: error: enum case 'ToJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:757:25: error: expression type '(Map, _)' is ambiguous without more context
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:759:8: error: enum case 'FromJSON' not found in type '<<error type>>'
/Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper/Core/Operators.swift:763:8: error: enum case 'ToJSON' not found in type '<<error type>>'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/llangfi1/Documents/Code/IOSDev/wooCommerce/Carthage/Checkouts/ObjectMapper/ObjectMapper.xcworkspace -scheme ObjectMapper-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by thii** [comment]
Could you try `carthage update --platform iOS --no-use-binaries`?

**Comment by thii** [comment]
Fixes in 503740966d1165fd22fdbaea4eb3fa824fb31eaf
